import numpy as np
arr = np.array(["Mahi","Tanya","Ayush"])
print(arr)
range01 = np.arange(15)
print(range01)
print("Min",range01.min())
print("Max",range01.max())
print("mean",range01.mean())
arr = range01.reshape(100,100)
print("Shape",arr)